### ISSUE TITLE
Operation name is different from Name

### ISSUE THREAD

**Issue by vladik-vitre** [coolhome/Hangfire.Extensions.ApplicationInsights#4]
All request telemetry seems to be collected in AI where Operation name is equal to Name
![image](https://user-images.githubusercontent.com/52456274/217508671-d546781d-a260-40a5-8f97-b376f2385256.png)
For some of the request telemetry, we have many Names under a specific Operation name
![image](https://user-images.githubusercontent.com/52456274/217509904-fea377db-a945-4f00-8d2c-0bcb0ad3ac5e.png)
Its always the same Operation name that they are under.

What can be the cause?

**Comment by vladik-vitre** [comment]
Hi @knopa, I saw you are working on this project lately, maybe you can help? Thanks!

**Comment by knopa** [comment]
If you check code. Extension set only Name.
Operation Name are handled by AI it self when it tried to operate with current Activity.Current which is potentially could be created by AI too and that means you have cascade job call tree - it's ok

**Comment by vladik-vitre** [comment]
First, thank you for the quick response. I really appreciate it.

I don't think I have a cascaded job, it looks like a bug because sometimes
it does run the same jobs outside of the root operation.
Maybe I don't understand what you mean when you say "cascade job call tree"?
I see that the jobs have the same Operation Id but they have nothing in
common as I see it.
In fact, the jobs get registered with the 'BulkLoadService.Import'
Operation name but this is a task that is created by a user and not a
scheduled one, there were no BulkLoadService.Import operations today yet I
see it as the Operation name of multiple unrelated jobs.

Also, for part of the time I see all jobs under the
'BulkLoadService.Import' Operation name and then some of the time it's
separate jobs as I want them and as they are.
I marked BulkLoadService.Import in Orange the and another operation that
comes sometimes under it in Pink, for some time it's under and suddenly
it's a regular operation...
[image: image.png]

**Comment by vladik-vitre** [comment]
The image that didn't go through the email for some reason...
![image](https://user-images.githubusercontent.com/52456274/217541923-19e51326-93be-4ad0-9377-ef7e2efdd5ec.png)

**Comment by knopa** [comment]
If they shared operation id - means it's start from same activity - as example job could be with ContinuationWith or inside same batch or another way of chaining execution

**Comment by vladik-vitre** [comment]
Usually when I see a chained telemetry, there is a root request and under it there are sub requests to a DB or something.
This is not the case be because there is no root request, all of the requests that share the operation id are at the same level in the tree.

I think that the BulkLoadService.Import somehow interferes with the telemetry, it seems like on every job of the BulkLoadService.Import type, the telemetry is switched from sharing an operation id between the telemetry data coming into AI to not sharing the operation id and vice versa.

This is why the Orange part is stopped in the graph and the Pink starts...
In the setup, we have three instances of an app service and all instances act the same, there is no instance that continues to use share operation id.

Really strange, there is no ContinueWith or a dependency, maybe it's a bug in the AI telemetry package and not this project?

**Comment by vladik-vitre** [comment]
We think we found the problem, waiting to see it resolves the issue....
In BulkLoadService.Import() there was some code the traces the import stages for use which used the telemetry client it got as a dependency injection,
`_telemetryClient.Context.Operation.Name = "BulkLoadService.Import";`
`_telemetryClient.Context.Operation.Id = Guid.NewGuid().ToString();`
Turns out the AddApplicationInsightsTelemetry() extension method calls AddTelemetryConfigAndClient(services) which does `services.AddSingleton<TelemetryClient>();`
This means the telemetry client is a singleton and we shouldn't mess with its Context,
We replaced the code with
`var depTelemetry = new DependencyTelemetry()`
`{`
`  Name = "TRACE-JOB BulkLoadService.Import",`
`};`
`var operation = _telemetryClient.StartOperation(depTelemetry);`

Another issue was that we didn't stop the operation at the end of the import so only a restart of the application or a new import was changing the Operation.Id so we also added `_telemetryClient.StopOperation(operation);` at the end of the method, after the import.

**Comment by knopa** [comment]
Seems you have custom code. because in that extension there is no mention issues

**Comment by vladik-vitre** [comment]
Our change fixed the problem, closing.
